services:
  qdrant:
    image: qdrant/qdrant:v1.12.5
    container_name: qdrant_fiap_rag
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  backend:
    build: .
    container_name: backend_fiap_rag
    env_file:
      - .env
    environment:
      QDRANT_URL: http://qdrant:6333
    ports:
      - "8000:8000"
    depends_on:
      - qdrant

volumes:
  qdrant_storage:
